name: Azure Web App Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: portfolio-old
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: portfolio-old

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: portfolio-old
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
